### ISSUE TITLE
Mac OS: version of duckdb seems wrong.

### ISSUE THREAD

**Issue by buseynehannes** [abhisek-de-capgemini/data-engineering-challenge-2023#1]
When I try loading the database with the given version (0.8.0) on macOS I get the following error:
```
Error: unable to open database "database.duckdb": IO Error: Trying to read a database file with version number 43, but we can only read version 51.
The database file was created with DuckDB version v0.7.0 or v0.7.1.
```

I've installed [duckdb_odbc-osx-universal.zip](https://github.com/duckdb/duckdb/releases/download/v0.7.1/duckdb_odbc-osx-universal.zip) and that was able to load the database.

**Comment by abhisek-de-capgemini** [comment]
Use version 0.7.1. Get it from --> [duckdb/v0.7.1](https://github.com/duckdb/duckdb/tree/v0.7.1)
